#!/usr/bin/env bash

function tag_deployment {
  CURRENT_TIMESTAMP=`date "+%Y%m%d%H%M%S"`
  TAG_NAME="deployed_$CURRENT_TIMESTAMP"
  git tag -a -m "Tagging deployment at $CURRENT_TIMESTAMP" $TAG_NAME
}

function verify_or_install_pygments {
  (port installed | grep "py25-pygments") || (echo "Missing pygments. Installing it..." && sudo port install py25-pygments)
}

verify_or_install_pygments && jekyll && rsync -avz --delete _site/ jasonrudolph.com:jasonrudolph.com && tag_deployment