#!/usr/bin/env bash

function tag_deployment {
  CURRENT_TIMESTAMP=`date "+%Y%m%d%H%M%S"`
  TAG_NAME="deployed_$CURRENT_TIMESTAMP"
  git tag -a -m "Tagging deployment at $CURRENT_TIMESTAMP" $TAG_NAME
}

function check_for_pygments {
  echo "Checking for pygments"
  port installed | grep "py25-pygments"
}

function confirm_prerequisites_or_exit {
  echo "Checking for prerequisites"

  check_for_pygments
  if [[ $? -ne "0" ]]; then
    echo "You must first install pygments via MacPorts"
    exit 1
  fi
}

confirm_prerequisites_or_exit && jekyll && rsync -avz --delete _site/ jasonrudolph.com:jasonrudolph.com && tag_deployment
